### ISSUE TITLE
Wallet getBalanceAvailable is returning null value

### ISSUE THREAD

**Issue by guilllet** [jnidzwetzki/bitfinex-v2-wss-api-java#123]
hello, I used the following piece of code for getting the available amount for a currency

```
for (final BitfinexWallet wallet : bitfinexWebsocketClient.getWalletManager().getWallets()) {
            if (wallet.getCurrency().equals(currency.getCurrency2())) {
                logger.info(wallet.toString());
                return wallet.getBalanceAvailable();
            }
        }
```
but the return value is null while getBalance() is returning 2327.6672216

[walletType=EXCHANGE, currency=USD, balance=2327.6672216, unsettledInterest=0, balanceAvailable=null]

thank you in advance

**Comment by mironbalcerzak** [comment]
I think `balanceAvailable` is used for margin trading - as **actual balance**, and **tradable balance** differs (due to ledger). 

-mb

**Comment by guilllet** [comment]
Ok but box do i get the available free amount in my wallet ?

**Comment by jnidzwetzki** [comment]
Bitfinex usually let some of the balance related fields empty in data updates. To get these values, you have to request the data. See https://github.com/jnidzwetzki/bitfinex-v2-wss-api-java/blob/master/EXAMPLES.md#request-wallet-balance for an example.
