### ISSUE TITLE
Connection state specific handlers introduced, externalize reconnection if needed

### ISSUE THREAD

**Issue by mironbalcerzak** [jnidzwetzki/bitfinex-v2-wss-api-java#126]
Hi Jan,
Been a while - hope you are doing all fine.

In this PR i've introduced 3 handlers that were missing.
- `onConnectionSuccess()`
- `onConnectionFailure()`
- `onDisconnection()`

Possible problem might arise if user decides mixing logic with `onConnectionStateChange(value)`... but we cannot do much  against "stupid"... :))

The main purpose of this PR is to externalize manual reconnection - for this reason I've introduced a flag `BitfinexWebsocketConfiguration#autoReconnect` which defaults to true.

have a good day,
- mb

**Comment by jnidzwetzki** [comment]
Hi Miron,

thank you very much for the refactoring and the introduction of the handlers. I merged your code a few minutes ago.

Best Regards
   Jan
