### ISSUE TITLE
Implement "BU" websocket event

### ISSUE THREAD

**Issue by mironbalcerzak** [jnidzwetzki/bitfinex-v2-wss-api-java#127]
Apparently, bitfinex introduced new event type - bu (balance-update).

https://docs.bitfinex.com/v2/reference#ws-auth-balance

worth handling it - for now, we log that event is not handled.

**Comment by jnidzwetzki** [comment]
A good point, I will have a look on this later.

**Comment by innsternet** [comment]
Getting this also popping up as a error
`ERROR com.github.jnidzwetzki.bitfinex.v2.callback.channel.AccountInfoHandler - No match found for message`

**Comment by jnidzwetzki** [comment]
@mironbalcerzak Good work, thank you very much. You code is merged.

Have a good weekend
   Jan

**Comment by Anarchotrader** [comment]
When new release?
