### ISSUE TITLE
Errors with derivatives

### ISSUE THREAD

**Issue by timvdd** [jnidzwetzki/bitfinex-v2-wss-api-java#168]
In BitfinexPair.java, something like below for the derivatives
`
	@Override
	public String toBitfinexString() {
                if(!currency2.equals("USTF0")){
                    return "t" + currency1 + currency2;
                }else{
                    return "t" + currency1 + ":" + currency2;
                }
	}
`

**Comment by jnidzwetzki** [comment]
Feature is implemented in the current snapshot version.
