### ISSUE TITLE
Question for Margin available

### ISSUE THREAD

**Issue by tojstein** [jnidzwetzki/bitfinex-v2-wss-api-java#19]
Hi. I cant figure out how to get 'margin available'. I've succesfully received my wallet data. Unfortunately it shows -1 in each field "balance available".  Example: [walletType=margin, curreny=USD, balance=1800.03706837, unsettledInterest=0.0, balanceAvailable=-1.0], Could you please provide me with guidance how to resolve this issue? It seems that this field is hardcoded

**Comment by jnidzwetzki** [comment]
Hi,

Thanks for your question. Some values are not automatically submitted by the Bitfinex API. The calculation of these values have to be requested explicit (see https://docs.bitfinex.com/v2/reference#ws-input-calc). This is currently not supported by this project, but I plan to add the support in the next version. 

If you have general questions about using the API implementation, feel free to join our chat at https://gitter.im/bitfinex-v2-wss-api-java/Lobby

Best Regards
    Jan

**Comment by jnidzwetzki** [comment]
Hi,

I added the support for the calculation request in the current snapshot version. You can request the missing field as follows:

```java
final BitfinexApiBroker bitfinexApiBroker = new BitfinexApiBroker("YOUR-API-KEY", "YOUR-API-SECRET");

bitfinexApiBroker.connect();
		
System.out.println(bitfinexApiBroker.getWalletManager().getWalletTable().get("margin", "USD"));
		
bitfinexApiBroker.getWalletManager().calculateWalletMarginBalance("USD");
		
// Wait some time until Bitfinex has send us a wallet update
Thread.sleep(TimeUnit.SECONDS.toMillis(5));
		
System.out.println(bitfinexApiBroker.getWalletManager().getWalletTable().get("margin", "USD"));

bitfinexApiBroker.close();
```

The output will be something like this:

```
Wallet [walletType=margin, curreny=USD, balance=XXXX.XX, unsettledInterest=0.0, balanceAvailable=-1.0]
Wallet [walletType=margin, curreny=USD, balance=XXXX.XX, unsettledInterest=0.0, balanceAvailable=XXXX.XX]
```
As you can see, the field is calculated and updated.

Best Regards
    Jan

**Comment by migunovAlex** [comment]
Hi Jan, appreciate such quick fix!

**Comment by tojstein** [comment]
Hi Jan, thank you very much!
Your code is really cool!
