### ISSUE TITLE
Missing precision due to floating-point arithmetic

### ISSUE THREAD

**Issue by hansblafoo** [jnidzwetzki/bitfinex-v2-wss-api-java#20]
I noticed it several times that rounding issues occur, e.g. while multiplying prices and amounts, which is caused by the limited precision even of double variables. These issues can cause trouble in working with Bitfinex as little rounding problems may lead to an exceeding of available balances and so on.

These problems are caused by the fact that all objects holding numerical values like prices, rates or amounts are using double values. In order to avoid this, the internal representation should be changed to BigDecimal which enables exact representation of numbers and thus exact calculations. However, this also requires that all processing steps like message parsing, value storage, message creation and internal processing must be done with BigDecimal without any intermediate conversion to a floating-point value like double.

**Comment by googya** [comment]
ask symbol price qty ETHBTC 0.0194460000000000014785950241957834805361926555633544921875 730.0988078300000552189885638654232025146484375

how to scale the precision

**Comment by Anarchotrader** [comment]
> ask symbol price qty ETHBTC 0.0194460000000000014785950241957834805361926555633544921875 730.0988078300000552189885638654232025146484375
> 
> how to scale the precision

For BigDecimal use this     .setScale(DigitsAfterPoint, RoundingMode.HALF_UP)
