### ISSUE TITLE
BitfinexCurrencyPair.registerDefaults() fails with error code 403

### ISSUE THREAD

**Issue by hhanh00** [jnidzwetzki/bitfinex-v2-wss-api-java#203]
Resources.toString(url) does not work well with HTTP URL

From the Guava doc https://guava.dev/releases/21.0/api/docs/com/google/common/io/Resources

> Provides utility methods for working with resources in the classpath. Note that even though these methods use URL parameters, they are usually not appropriate for HTTP or other non-classpath resources.

Specifically, Bitfinex requires passing a user agent.

**Comment by jnidzwetzki** [comment]
Thanks for the PR and the contribution (#204). Looks good and is merged.
