### ISSUE TITLE
Add leverage to derivative order

### ISSUE THREAD

**Issue by wgolyakov** [jnidzwetzki/bitfinex-v2-wss-api-java#235]
From documentation:
https://docs.bitfinex.com/reference#ws-auth-input-order-new
lev | int | Set the leverage for a derivative order, supported by derivative symbol orders only. The value should be between 1 and 100 inclusive. The field is optional, if omitted the default leverage value of 10 will be used.

**Comment by jnidzwetzki** [comment]
Hi @wgolyakov,

thank you very much the PR that implements the feature. 

Best Regards
   Jan
