### ISSUE TITLE
The checksum and sequence parametes

### ISSUE THREAD

**Issue by tojstein** [jnidzwetzki/bitfinex-v2-wss-api-java#24]
Hi Jan!
I could not to find the request for checksum and sequence parameter with the following event {"event":"conf", "flags":131072} and {"event":"conf","flags":"65536"} for OrderBook according to this https://docs.bitfinex.com/v2/docs/ws-general#section-available-options. Was it implemented into your library?   

Regards, Sergey.

**Comment by jnidzwetzki** [comment]
Hello Sergey,

Unfortunately, both features are currently not implemented. Sequencing should be easy to implement. I will add this feature during the next days.

Regarding the orderbook checksumming: Currently, the implementation only forwards orderbook entries and does not build an orderbook itself. To verify the checksum, we need an orderbook with at least 25 entries. 

Do you have already written an implementation for collecting orderbook entries and build a proper orderbook? If so, would you share your code? I would be happy to add this to the project. Then we could use the orderbook to calculate the checksum.

Best Regards
    Jan

**Comment by jnidzwetzki** [comment]
Hello Sergey,

The last snapshot version contains the `sequence number auditing` feature. You can enable this as follows:

```java

final ConnectionFeatureManager cfManager = bitfinexClient.getConnectionFeatureManager();

final SequenceNumberAuditor sequenceNumberAuditor = bitfinexClient.getSequenceNumberAuditor();
sequenceNumberAuditor.setErrorPolicy(SequenceNumberAuditor.ErrorPolicy.LOG_ONLY);

cfManager.enableConnectionFeature(BitfinexConnectionFeature.SEQ_ALL);
```

Best Regards
   Jan

**Comment by jnidzwetzki** [comment]
Hello Sergey,

When you have a working orderbook implementation, I would be happy when you open a pull request. I think that's an interesting feature for a lot of people. 

I have prepared the checksum feature in the API implementation, so we can just add that to the orderbook.

Best Regards
    Jan
