### ISSUE TITLE
Sequence number concurrent update

### ISSUE THREAD

**Issue by migunovAlex** [jnidzwetzki/bitfinex-v2-wss-api-java#27]
Hi Jan!
I figured out an issue related to Sequence number update. It might be that it updates as normal, then it  stucks at the same number and for couple of messages it is the same. Then It updates. So, the behavior looks like it does not properly work with concurrent data receiving. 

Steps To Reproduce:
I tested it with orderbook subscription. I subscribed to couple of Currency Pairs. And when I started to receive big amount of messages sequence number started to have a problem.

My observations:
Class BitFinexApiBroker contains this method. I use this code to connect to differemt currency pairs feed;
```
private void handleChannelCallback(final String message) {
		// Channel callback
		logger.debug("Channel callback");
		updateConnectionHeartbeat();

		// JSON callback
		final JSONTokener tokener = new JSONTokener(message);
		final JSONArray jsonArray = new JSONArray(tokener);
	    if(connectionFeatureManager.isConnectionFeatureActive(BitfinexConnectionFeature.SEQ_ALL)) {
			sequenceNumberAuditor.auditPackage(jsonArray);
		}
		final int channel = jsonArray.getInt(0);	
		if(channel == 0) {
			handleSignalingChannelData(message, jsonArray);
		} else {
			handleChannelData(jsonArray);
		}
	}
```
sequenceNumberAuditor.auditPackage(jsonArray); updates sequence number and then pushes message to parsing. If there are more than one thread invokes this method and might invoke auditPackage before previous one will finish parsing messages.

```
final OrderbookConfiguration orderbookConfiguration = new OrderbookConfiguration(f.getCurrencyPair().getBitfinexCurrencyPair(), OrderBookPrecision.P0, OrderBookFrequency.F0, 25);

            final OrderbookManager orderbookManager = bitfinexApiBroker.getOrderbookManager();

            final BiConsumer<OrderbookConfiguration, OrderbookEntry> callback = (orderbookConfig, entry) -> {
                long publicSequence = sequenceNumberAuditor.getPublicSequence();
                OrderBook orderBook = convertOrderBook(entry, f.getCurrencyPair(), publicSequence);
                orderBookService.pushForCalculation(orderBook);
                System.out.println("Got a sequence number - " + publicSequence);
            };

            try {
                ConnectionFeatureManager cfManager = bitfinexApiBroker.getConnectionFeatureManager();
                sequenceNumberAuditor = bitfinexApiBroker.getSequenceNumberAuditor();

                sequenceNumberAuditor.setErrorPolicy(SequenceNumberAuditor.ErrorPolicy.LOG_ONLY);
                cfManager.enableConnectionFeature(BitfinexConnectionFeature.SEQ_ALL);

                orderbookManager.registerOrderbookCallback(orderbookConfiguration, callback);
                orderbookManager.subscribeOrderbook(orderbookConfiguration);
            } catch (Exception e) {
                logger.error("Error while trying to subscribe to Bitfinex {} currency pair OrderBook", f.getCurrencyPair().getStringFormat());
            }
```

So, when I get sequence number here it might be wrong. I guess it is better to send Some Wrapper object on top of OrderBook object which can contain such number, or list of OrderBook objects with one field which is sequence and push these values in time of object creating.

**Comment by jnidzwetzki** [comment]
Hello migunovAlex,

Thanks for your message. I am not sure I understand the problem correctly. The `WebsocketClientEndpoint` works single-threaded. Therefore, all messages passed to the `BitfinexApiBroker` are guaranteed to be in-order. This is the point where the `SequenceNumberAuditor` audits the sequence number. Then, the message is processed and forwarded to the consumers of the `BitfinexApiBroker`. This is done in a concurrent (out-of-order) way and calling `sequenceNumberAuditor.getPublicSequence()` does not guarantee, that you get the sequence number that is related to the callback.

However, the `SequenceNumberAuditor` guarantees that all sequence numbers are audited and no message is lost. You do not have to check the numbers yourself. To test if everything is fine until now, you can simply call `sequenceNumberAuditor.isFailed()`. In addition you could set `sequenceNumberAuditor.setErrorPolicy(SequenceNumberAuditor.ErrorPolicy.RUNTIME_EXCEPTION)`. Then a run-time exception is thrown as soon as a lost message is detected. 

Could you describe why you need the SequenceNumbers in a callback? Do you try to order the callbacks? Is there any use-case that I miss?

Best Regards
   Jan
