### ISSUE TITLE
Issue with order amount after BigDecimal migration

### ISSUE THREAD

**Issue by migunovAlex** [jnidzwetzki/bitfinex-v2-wss-api-java#29]
Hi Jan!

This guy is critical:
When I submit an order I get this error:
`Got Error message: [0,"n",[1523955674172,"on-req",null,null,[null,null,1523955674030000,null,null,null,-5.95861881,null,"LIMIT",null,null,null,null,null,null,null,68.856,null,null,null,null,null,null,0,0,null,null,null,null,null,null,null],null,"ERROR","amount: invalid"]]`

Then I put a break point into BitfinexApiBroker.sendCommand() after final String generation. And I got this record:
`[0,"on", null, {"symbol":"tBTCUSD","amount":0.01,"hidden":0,"price":6800,"type":"LIMIT","cid":1523967707187000}]`

Then I rolled back to version 0.6.1 and got message at the same breakPoint:
`[0,"on", null, {"symbol":"tBTCUSD","amount":"0.01","hidden":0,"price":"6800.0","type":"LIMIT","cid":1523968320583000}]`

Looks like amount now serialized in another way cause now it is BigDecimal

**Comment by jnidzwetzki** [comment]
Hello migunovAlex,

Thank you for pointing that out. Could you check if the problem has been fixed in the current snapshot version?

Best Regards
    Jan

**Comment by tojstein** [comment]
Hi Jan!

Thanks for your fix!
Yes, it works for an amount, but there is the same bug for the price. Probably, just need to add same changes for price.

Regards,
Sergey.

**Comment by jnidzwetzki** [comment]
Hello Sergey,

This issue is now fixed in the snapshot version. Could you try if anything works as expected? 

Best Regards
    Jan

**Comment by jnidzwetzki** [comment]
Hello Sergey,

I have tested the order function in the last snapshot release. It seems to be working now. If you have still problems with the function, please re-open this issue.

Best Regards
    Jan

**Comment by tojstein** [comment]
Hi Jan!

Thank you!
Yes, your fix for a price works!
I'm sorry, couldn't answer quickly.

Regards,
Sergey.
