### ISSUE TITLE
Simple call

### ISSUE THREAD

**Issue by hub8git** [jnidzwetzki/bitfinex-v2-wss-api-java#34]
Hello,
What class can I use to simply send a command (request) to the server and get an answer, in the data class?
Similarly, the API:
https://github.com/joaopsilva/binance-java-api

**Comment by jnidzwetzki** [comment]
Hello hub8git,

This project uses a different approach. The available commands are distributed among different classes. The first step is to create an instance of the class `BitfinexApiBroker`. Afterward, you can use different managers (like the `QuoteManager` or the `OrderManager`) to perform your operations. 

You will find some examples here: 
https://github.com/jnidzwetzki/bitfinex-v2-wss-api-java/blob/master/EXAMPLES.md

Best Regards
   Jan
