### ISSUE TITLE
missing mappings

### ISSUE THREAD

**Issue by mironbalcerzak** [jnidzwetzki/bitfinex-v2-wss-api-java#41]
Greets,
Following currency mappings are missing:

ABS:ETH
ABS:USD
ATM:ETH
AUC:ETH
BNT:ETH
CBT:ETH
CND:ETH
CTX:ETH
DAD:BTC
DAD:ETH
DTA:ETH
ESS:ETH
FSN:ETH
HOT:ETH
IQX:USD
KNC:ETH
KNC:USD
LYM:ETH
LYM:USD
MAN:ETH
MAN:USD
MKR:ETH
MKR:USD
NCA:ETH
ORS:ETH
ORS:USD
POA:ETH
POY:ETH
POY:USD
SEE:BTC
SEE:ETH
SEN:ETH
UTK:ETH
UTK:USD
VEE:ETH
VEN:ETH
VEN:USD
WPR:ETH
XRA:ETH
XRA:USD
ZCN:ETH
ZIL:ETH
ZIL:USD

PS.Wouldn't it be better to refactor BitfinexCurrencyPair and dynamically build it? (maybe "register" method -- there's a REST API that could populate it: https://api.bitfinex.com/v1/symbols_details)

Great job on the lib - thank you big time :)

mb

**Comment by jnidzwetzki** [comment]
Hi,

Thanks for your report. I've also thought about creating this list dynamically. The currency pairs have been changing quite a lot these days. 

Right now I'm on vacation. After that, I'm gonna refactor this part of the library. 

Best Regards
   Jan

**Comment by mironbalcerzak** [comment]
I've refactored it - hopefully it's good enough :)

mb
