### ISSUE TITLE
my account have  enough balance ; but i use programs create order fail

### ISSUE THREAD

**Issue by MisterChangRay** [jnidzwetzki/bitfinex-v2-wss-api-java#53]
my account have  enough balance ; but i use programs create order; return {"message":"Invalid order: not enough tradable balance for 0.002 BTCUSD at 6200.0"};;;;;;
but  I order manually normal
why? pls

**Comment by jnidzwetzki** [comment]
Hi,

Bitfinex offers two types of trades: market and exchange trades. The market trades use your market wallet, the exchange trades use your margin wallet. Please check that the correct wallet has enough balance and you use the right order type.

Best Regards
   Jan

**Comment by MisterChangRay** [comment]
oky; this problem has been fix;  thanks
