### ISSUE TITLE
RawOrderbookConfiguration

### ISSUE THREAD

**Issue by Flexz9** [jnidzwetzki/bitfinex-v2-wss-api-java#7]
Looks like RawOrderbookConfiguration returns the wrong values:
entry.getPrice() -> id
entry.getAmount() -> amount
entry.getCount() -> price

when the getCount (price) = 0, I assume its because that order is removed/completed

**Comment by jnidzwetzki** [comment]
Thanks for the hint, I will fix this during the next days

**Comment by jnidzwetzki** [comment]
Hi, 

In the last snapshot version, I added a `RawOrderbookManager` (see https://github.com/jnidzwetzki/bitfinex-v2-wss-api-java/blob/master/EXAMPLES.md - Section: Subscribe raw orderbook stream) and the entity `RawOrderbookEntry`. Does this fix your problem?

Best Regards
   Jan

**Comment by Flexz9** [comment]
I can not use that yet, I'm using maven 0.5.2

**Comment by jnidzwetzki** [comment]
Hi,

Thanks for your feedback. Please try it again with the next version (0.5.3) which will be released tomorrow.

Best Regards
    Jan
