### ISSUE TITLE
Callback order EXCHANGE_MARKET amount bought

### ISSUE THREAD

**Issue by Flexz9** [jnidzwetzki/bitfinex-v2-wss-api-java#8]
Hello,

How can you see the amount of bought currency when an order is finished?
I'm doing a callback, but im not feeling it to try things out to figure out what everything is at this moment.

Like I want to buy BTC, I have 50$, how would you buy BTC, and knowing in the callback how much you bought?

**Comment by jnidzwetzki** [comment]
Hello,

Parsing `trade executed` or `trade update` messages is currently not implemented in this project. This might be part of one of the next versions. 

Best Regards
   Jan
