### ISSUE TITLE
EXAMPLES.md not up-to-date

### ISSUE THREAD

**Issue by rufsam** [jnidzwetzki/bitfinex-v2-wss-api-java#84]
Seems like the EXAMPLES.md is not up-to-date.

Following method in **Connecting and authorizing** does not exist:
BitfinexWebsocketClient client = BitfinexClientFactory.**newSingleClient(config);**

Following method in **Connection Features** does not exist:
final SequenceNumberAuditor sequenceNumberAuditor = bitfinexClient.getSequenceNumberAuditor();

I haven't checked the EXAMPLES.md for other errors, but I would appreciate it if you could have a look at it :)

**Comment by mironbalcerzak** [comment]
good catch -  this option was moved to config itself :)

**Comment by jnidzwetzki** [comment]
Thank you for pointing that out. I will update the documentation right now.

**Comment by rufsam** [comment]
Perfect, many thanks for your work. Love this library.
