### ISSUE TITLE
Order update functionality

### ISSUE THREAD

**Issue by migunovAlex** [jnidzwetzki/bitfinex-v2-wss-api-java#88]
Hi Jan!

Just a quick question. I was trying to update submitted order and as I can see method updateOrder in OrderManager class just add an order to internal order list, however does not send any request with update to Bitfinex using client as it is implemented in placeOrder or cancelOrder methods:
`client.sendCommand(orderNewCommand);`
Am I right? If no, could you point me to the update order functionality

**Comment by mironbalcerzak** [comment]
Hi.
There is no update functionality. You need to cancel old order and create new one.
Hope it helps yr case.
- mb

**Comment by migunovAlex** [comment]
Hi! Thank you for the information. But is is going to be implemented in future releases? The method name is confusing - you expect to update, however not in internal list but a real order

**Comment by mironbalcerzak** [comment]
Thanks for letting us know - yeah - hopefully we will cover all API at some point - cannot specify any time frames though.

**Comment by migunovAlex** [comment]
Thank you! So closing this for now
