### ISSUE TITLE
Don't recieve ticker information for all pairs

### ISSUE THREAD

**Issue by CheremisinVlad** [jnidzwetzki/bitfinex-v2-wss-api-java#92]
Hello!First of all thanks for great library.
 I have some issue.
I need subscribe three callback(order book,trades and current ticker information) for every pair on exchange.
I create single **BitfinexWebsocketClient** instance for it.
```
BitfinexWebsocketClient client= BitfinexClientFactory.newPooledClient(config,249);
client.connect();
 BitfinexCurrencyPair.registerDefaults()
```

Next i subscribe all pairs
```
Collection<BitfinexCurrencyPair> symbols = BitfinexCurrencyPair.values();
        ExecutorService service = Executors.newFixedThreadPool(symbols.size()+1);
        final QuoteManager quoteManager = client.getQuoteManager();
        final BiConsumer<BitfinexTickerSymbol, BitfinexTick> volCallback = getTickCallback();

        for (BitfinexCurrencyPair pair:symbols) {
            service.submit(() -> {
                BitfinexTickerSymbol symbol = BitfinexTickerSymbol.fromBitfinexString(pair.toBitfinexString());
                quoteManager.registerTickCallback(symbol, volCallback);
                quoteManager.subscribeTicker(symbol);
                return "true";
            });
        }
```

The same code i write for order book and executed trades.
But i don't recieve information for some pairs like tBTCUSD or tETHUSD, although almost all work correctly.
Is any idea what i'm doing wrong?Thanks in advance

**Comment by CheremisinVlad** [comment]
Thanks a lot.Sorry for stupid question

**Comment by mironbalcerzak** [comment]
no such thing as stupid question :) best of lucks and comment here if this solved your issue.

-- mb
